btree: Fix entry peek_forward()/peek_backward() lifetime
To defence against unexpected behavior.

Previous this example can compile but get changed value from immutable reference.

error[E0505]: cannot move out of `ent` because it is borrowed
    |
246 |             Entry::Vacant(ent) => {
    |                           --- binding `ent` declared here
...
294 |                 if let Some((_next_start, _next_size)) = ent.peek_forward() {
    |                                                          --- borrow of `ent` occurs here
...
298 |                             ent.insert(*size);
    |                             ^^^ move out of `ent` occurs here
299 |                             next_offset.replace(*_next_start);
    |                                                 ------------ borrow later used here